name: geo_attendance_system
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.5
  connectivity_wrapper: ^1.1.0
  flutter_screenutil: ^5.6.0
  fluttertoast: ^8.1.1
  permission_handler: ^10.2.0
  shared_preferences: ^2.0.15
  dio: ^4.0.6
  json_annotation: ^4.7.0
  flutter_spinkit: ^5.1.0
  # get_version: ^0.2.2
  sqflite: ^2.2.0+2
  image_picker: ^0.8.6
  path_provider: ^2.0.11
  intl: ^0.17.0
  meta: ^1.8.0
  geolocator: ^9.0.2
  google_mlkit_face_detection: ^0.4.0
  tflite_flutter: ^0.9.0
  camera: ^0.10.0+4
  image: ^3.2.2
  flutter_background_service: ^2.4.5
  package_info_plus: ^1.4.2
  android_alarm_manager_plus: ^2.1.0
  #geocoder: any
  group_radio_button: ^1.2.0
  month_picker_dialog:
    path: lib/custom_packages/month_picker_dialog-0.4.0
    version: 0.4.0
  table_calendar: ^3.0.8
  connectivity: ^3.0.6
  search_choices: ^2.1.5
  platform_device_id: ^1.0.1
  date_time_picker: ^2.1.0
  grouped_list: ^5.1.2
  csv: ^5.0.1
  location: ^4.4.0
  flutter_local_notifications: ^12.0.3
#  open_file: ^3.2.1
  external_path: ^1.0.3
  toggle_switch: ^2.0.1
  open_filex: ^4.4.0
  google_mlkit_commons: ^0.2.0
  device_info_plus: ^4.0.0
  wakelock: ^0.6.2
  geocoding: ^2.1.1



dev_dependencies:
  flutter_test:
    sdk: flutter
#  floor_generator: any
#  build_runner: any
#  analyzer: any



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


#name: geo_attendance_system
#description: A new Flutter project.
#
## The following line prevents the package from being accidentally published to
## pub.dev using `pub publish`. This is preferred for private packages.
#publish_to: 'none' # Remove this line if you wish to publish to pub.dev
#
## The following defines the version and build number for your application.
## A version number is three numbers separated by dots, like 1.2.43
## followed by an optional build number separated by a +.
## Both the version and the builder number may be overridden in flutter
## build by specifying --build-name and --build-number, respectively.
## In Android, build-name is used as versionName while build-number used as versionCode.
## Read more about Android versioning at https://developer.android.com/studio/publish/versioning
## In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
## Read more about iOS versioning at
## https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#version: 1.0.2+1
#
#environment:
#  sdk: ">=2.6.0 <3.0.0"
#
#dependencies:
#  flutter:
#    sdk: flutter
#
#  get: ^4.6.5
#  connectivity_wrapper: ^1.1.4
#  flutter_screenutil: ^5.7.0
#  fluttertoast: ^8.2.4
#  permission_handler: ^11.0.1
#  shared_preferences: ^2.2.2
#  dio: ^5.4.0
#  json_annotation: ^4.8.1
#  flutter_spinkit: ^5.2.0
#  wakelock: ^0.6.2
#  # get_version: ^0.2.2
#  sqflite: ^2.2.8+4
#  image_picker: ^1.0.4
#  path_provider: ^2.0.15
#  intl: ^0.17.0
#  meta: ^1.8.0
#  geolocator: ^10.1.0
#  google_mlkit_face_detection: ^0.9.0
#  tflite_flutter: ^0.9.1
#  camera: ^0.10.5+5
#  image: ^4.1.6
#  flutter_background_service: ^5.0.5
#  package_info_plus: ^1.4.2
#  android_alarm_manager_plus: ^3.0.4
#  #geocoder: any
#  group_radio_button: ^1.3.0
#  month_picker_dialog:
#    path: lib/custom_packages/month_picker_dialog-0.4.0
#    version: 0.4.0
#  table_calendar: ^3.0.8
#  connectivity: ^3.0.6
#  search_choices: ^2.2.7
#  platform_device_id: ^1.0.1
#  date_time_picker: ^2.1.0
#  grouped_list: ^5.1.2
#  csv: ^5.1.1
#  location: ^5.0.3
#  flutter_local_notifications: ^8.2.0
#  open_file_safe : ^3.2.3
#  external_path: ^1.0.3
#  toggle_switch: ^2.1.0
#  google_mlkit_commons: ^0.6.1
#  device_info_plus: ^4.0.0
#  geocoding: ^2.1.1
#
#
#
#dev_dependencies:
#  flutter_test:
#    sdk: flutter
##  floor_generator: any
##  build_runner: any
##  analyzer: any
#
#
#
## For information on the generic Dart part of this file, see the
## following page: https://dart.dev/tools/pub/pubspec
#
## The following section is specific to Flutter.
#flutter:
#
#  # The following line ensures that the Material Icons font is
#  # included with your application, so that you can use the icons in
#  # the material Icons class.
#  uses-material-design: true
#
#  # To add assets to your application, add an assets section, like this:
#  assets:
#    - assets/
#
#  # An image asset can refer to one or more resolution-specific "variants", see
#  # https://flutter.dev/assets-and-images/#resolution-aware.
#
#  # For details regarding adding assets from package dependencies, see
#  # https://flutter.dev/assets-and-images/#from-packages
#
#  # To add custom fonts to your application, add a fonts section here,
#  # in this "flutter" section. Each entry in this list should have a
#  # "family" key with the font family name, and a "fonts" key with a
#  # list giving the asset and other descriptors for the font. For
#  # example:
#  # fonts:
#  #   - family: Schyler
#  #     fonts:
#  #       - asset: fonts/Schyler-Regular.ttf
#  #       - asset: fonts/Schyler-Italic.ttf
#  #         style: italic
#  #   - family: Trajan Pro
#  #     fonts:
#  #       - asset: fonts/TrajanPro.ttf
#  #       - asset: fonts/TrajanPro_Bold.ttf
#  #         weight: 700
#  #
#  # For details regarding fonts from package dependencies,
#  # see https://flutter.dev/custom-fonts/#from-packages
